### PR TITLE
fix parsePath

### PR DESCRIPTION
**Pull request by tforkmann**
Fix for #55

### CODE REVIEW

**Comment by et1975** [comment]
Looking at your stacktrace, I kinda doubt that this change addresses the problem - `parseParams` seems to be where it hits.

**Comment by et1975** [comment]
See if you can create a failing test in [urlParser](https://github.com/elmish/urlParser/blob/master/tests/Tests.fs)

**Comment by tforkmann** [comment]
@et1975 I were able to fix the test project. Now it actually runs the tests. Sadly I got lost and I'm not sure how to add a correct test case for that specific issue. https://github.com/elmish/urlParser/pull/22

**Comment by et1975** [comment]
@tforkmann let's track this in urlParser repo, I don't think the changes you have here would do anything for your problem.

**Pull request closed without merging**
